### ISSUE TITLE
pipreqsnb failing

### ISSUE THREAD

**Issue by paulaceccon** [ivanlen/pipreqsnb#21]
```
pipreqsnb                                                     main         10:11:08  
Traceback (most recent call last):
  File "/Users/paulaceccon/Documents/Projects/ml-helper-scripts/ml-helper/lib/python3.7/site-packages/pipreqsnb/pipreqsnb.py", line 122, in main
    for n_cell, cell in enumerate(nb['cells']):
KeyError: 'cells'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/paulaceccon/Documents/Projects/ml-helper-scripts/ml-helper/bin/pipreqsnb", line 11, in <module>
    load_entry_point('pipreqsnb==0.2.3', 'console_scripts', 'pipreqsnb')()
  File "/Users/paulaceccon/Documents/Projects/ml-helper-scripts/ml-helper/lib/python3.7/site-packages/pipreqsnb/pipreqsnb.py", line 128, in main
    print("Exception occurred while working on file {}, cell {}/{}".format(nb_file, n_cell + 1, len(nb['cells'])))

```

**Comment by ivanlen** [comment]
It seems to me that you are targeting and empty notebook. Could that be the problem?

**Comment by ivanlen** [comment]
I close the issue, if you still are finding this problem please reopen.
