### ISSUE TITLE
SyntaxError for multiline imports

### ISSUE THREAD

**Issue by jakubpernis** [ivanlen/pipreqsnb#26]
I encountered error when I have multiline imports in my notebook (typical when using e.g. black as I'm using). The example notebook `Imports.ipynb` has only one cell:
```
from sklearn.model_selection import (
    GridSearchCV,
    RandomizedSearchCV,
    StratifiedShuffleSplit,
)
from sklearn.neighbors import KNeighborsRegressor
```
and when I run `pipreqsnb Imports.ipynb` I get

```
pipreqs  --savepath requirements.txt /Users/jakubpernis/notebooks/__temp_pipreqsnb_folder
ERROR: Failed on file: /Users/jakubpernis/notebooks/__temp_pipreqsnb_folder/_pipreqsnb_temp_file.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/pipreqs", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pipreqs/pipreqs.py", line 488, in main
    init(args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pipreqs/pipreqs.py", line 415, in init
    candidates = get_all_imports(input_path,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pipreqs/pipreqs.py", line 131, in get_all_imports
    raise exc
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pipreqs/pipreqs.py", line 117, in get_all_imports
    tree = ast.parse(contents)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 2
    from sklearn.neighbors import KNeighborsRegressor
    ^
SyntaxError: invalid syntax
```
However when I don't use the formatter and keep the import on one line it works just fine: 
```
pipreqsnb Imports.ipynb
pipreqs  --savepath requirements.txt /Users/jakubpernis/notebooks/__temp_pipreqsnb_folder
INFO: Successfully saved requirements file in requirements.txt
```

I'm using pipreqsnb 0.2.4.

**Comment by ivanlen** [comment]
It seems to be a problem of `pipreqs`, and since this lib uses it under the hood thats might be the reason of the error.
Let me investigate and try to see if I can do some workaround to fix this.

**Comment by KonradSzafer** [comment]
I encountered a similar problem with multi-line imports without curly brackets, where the imports were separated by a "/".

**Comment by IsaacCheng9** [comment]
> It seems to be a problem of `pipreqs`, and since this lib uses it under the hood thats might be the reason of the error. Let me investigate and try to see if I can do some workaround to fix this.

This bug only seems to occur when you do multi-line imports in Jupyter Notebooks – it works fine (both `pipreqs` and `pipreqsnb`) when a multi-line import is in a regular Python file.

For example, with the following imports, it causes an error in the Jupyter Notebook:
```python
from sklearn.metrics import (
    accuracy_score,
    f1_score,
    mean_absolute_error,
    r2_score,
    silhouette_score,
)
```

```
    from sklearn.metrics import (
                                ^
SyntaxError: '(' was never closed
```
