### ISSUE TITLE
cannot work on "from ... import (...)"

### ISSUE THREAD

**Issue by sumowi** [ivanlen/pipreqsnb#30]
just like:

`from sklearn.preprocessing import (
    StandardScaler,
    QuantileTransformer,
    Normalizer,
    MinMaxScaler,
    PolynomialFeatures,
)

from sklearn.inspection import permutation_importance as impt`

will SyntaxError:
`ERROR: Failed on file: ./__temp_pipreqsnb_folder/_pipreqsnb_temp_file.py
Traceback (most recent call last):
  File "/home/myf/mambaforge/envs/skorch/bin/pipreqs", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/myf/mambaforge/envs/skorch/lib/python3.11/site-packages/pipreqs/pipreqs.py", line 528, in main
    init(args)
  File "/home/myf/mambaforge/envs/skorch/lib/python3.11/site-packages/pipreqs/pipreqs.py", line 455, in init
    candidates = get_all_imports(input_path,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/myf/mambaforge/envs/skorch/lib/python3.11/site-packages/pipreqs/pipreqs.py", line 131, in get_all_imports
    raise exc
  File "/home/myf/mambaforge/envs/skorch/lib/python3.11/site-packages/pipreqs/pipreqs.py", line 117, in get_all_imports
    tree = ast.parse(contents)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/myf/mambaforge/envs/skorch/lib/python3.11/ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<unknown>", line 12
    from sklearn.inspection import permutation_importance as impt
    ^^^^
SyntaxError: invalid syntax`

**Comment by d-kleine** [comment]
Same issue here.
@ivanlen Is this repo still maintained?
