### ISSUE TITLE
Parses non .ipynb  python files

### ISSUE THREAD

**Issue by jpyrett** [ivanlen/pipreqsnb#5]
There are some valid .py files this is breaking on when it tries to parse the file.
Such as one with plaidml.      [https://github.com/plaidml/plaidml/blob/master/bzl/version.tpl.py](https://github.com/plaidml/plaidml/blob/master/bzl/version.tpl.py)

ERROR: Failed on file: ./bazel-plaidml/bzl/version.tpl.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/pipreqs", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pipreqs/pipreqs.py", line 470, in main
    init(args)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pipreqs/pipreqs.py", line 406, in init
    candidates = get_all_imports(input_path,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pipreqs/pipreqs.py", line 138, in get_all_imports
    raise exc
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pipreqs/pipreqs.py", line 124, in get_all_imports
    tree = ast.parse(contents)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/ast.py", line 47, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 3
    {PREFIX}_VERSION = "{VERSION}"
            ^
SyntaxError: invalid syntax

**Comment by jpyrett** [comment]
The glob.glob code and following line to open a .ipynb file and the args parser code is broken.  Which is why it is trying to read all other files. Closing.
