### ISSUE TITLE
Key:  cells is missing

### ISSUE THREAD

**Issue by jpyrett** [ivanlen/pipreqsnb#6]
(base) Yours-Mac-Pro:plaidml jpyrett$ pipreqsnb --ignore ./bazel-plaidml/ .
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/bin/pipreqsnb", line 11, in <module>
    load_entry_point('pipreqsnb==0.1.2', 'console_scripts', 'pipreqsnb')()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pipreqsnb/pipreqsnb.py", line 53, inmain
    for cell in nb['cells']:
KeyError: 'cells'

**Comment by jpyrett** [comment]
This is due to the path  glb.glob and --ignore dirs not working of the other issue. Closing this.
